services:
  mediarch:
    build: .
    image: mediarch:0.2.0
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=mediarch
      - DB_USER=mediarch_user
      - DB_PASSWORD=mediarch_password
    depends_on:
      - mariadb
    volumes:
      - /app/node_modules
      - ./storage/mediarch/uploads:/app/public_html/uploads
      - ./storage/mediarch/upload_parts:/app/public_html/upload_parts
    networks:
      - mediarch_network

  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mediarch
      MYSQL_USER: mediarch_user
      MYSQL_PASSWORD: mediarch_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db/create_database_structure.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - mediarch_network

volumes:
  db_data:

networks:
  mediarch_network:
    driver: bridge